name: ci

on:
    push:
    workflow_dispatch:
    schedule:
      - cron: '0 9 * * *'  # Run every day at 9am UTC

jobs:
    build:  
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v4
          - name: Set up JDK 18 for x64
            uses: actions/setup-java@v3
            with:
                java-version: '18'
                distribution: 'temurin'
                architecture: x64

          - name: Install
            run: mvn -B clean install

          - name: Package
            run: mvn package

          - name: Install FOSSA CLI
            run: |
                curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash

          - name: Check FOSSA CLI Version
            run: fossa -V

          - name: Run Analysis (in debug mode) (and output mode)
            run: fossa analyze -o --debug

          - name: Run Analysis (in debug mode)
            run: fossa analyze --debug
